### ISSUE TITLE
Can not install any modules

### ISSUE THREAD

**Issue by t0rzz** [Fox2Code/FoxMagiskModuleManager#167]
Since version 0.5.0 it seems like installation from local memory is not possible.
When selecting the package, Fox's MM crashes with the following log:

`FATAL EXCEPTION: main
Process: com.fox2code.mmm, PID: 2050
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at w00.run(SourceFile:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

Magisk version: latest stable as of today.
Android version: 12
Zigysk enabled.

Thank you

**Comment by Fox2Code** [comment]
Hi, I was able to find the `NullPointerException` issue, but it has only to do with the error screen, I will investigate more for local install issue.

You should have seen `! File is not a valid Magisk module or AnyKernel3 zip` in terminal.

**Comment by Fox2Code** [comment]
I test and local install is working on `0.5.1`, can you send the module zip file please.

**Comment by t0rzz** [comment]
> I test and local install is working on `0.5.1`, can you send the module zip file please.

Is there a way to share it privately? It's a paid magisk module.

**Comment by Fox2Code** [comment]
You can DM me on this chat: https://t.me/Fox2Code_Chat
But I still would like contacting the original author directly if possible.

**Comment by Fox2Code** [comment]
Thx, this issue has 2 separate bugs, both fixed now!
