### ISSUE TITLE
[BUG] v.1.0.1 crashes

### ISSUE THREAD

**Issue by andigenn** [Fox2Code/FoxMagiskModuleManager#244]
**Describe the bug**
v.1.0.1 crashes

**To Reproduce**
1. Try to open app
2. See error

**Expected behavior**
That the app opens correctly

**Device info(please complete the following information):**
 - Device: [Xiaomi Mi 8]
 - OS: [MIUI Global 12.0.3]
 - App Version [1.0.1 latest]

**Comment by Clasimodo** [comment]
Same here on Samung A70

**Comment by bat-deluxe** [comment]
Same for me, keep crashing.
i tried 3 different version, crashing on launch but by going in settings and more settings in this app, the app not crash..

Oneplus 7 Pro
Android 11

**Comment by clexanis** [comment]
I also got this after updating.
Notifications worked but opening the application itself or any notifications would crash after briefly showing a report form.

#### Temporary solution 
I solved it by deleting the application data in the phone settings.

#### Device info
- Device: Xiaomi Redmi Note 8 Pro
- OS: crDroid 9 "2022-11-19"
- App version: 1.0.1-arm64-v8

**Comment by Clasimodo** [comment]
Deleting the application data in the phone setting doesn't work for me. Went back to previous version.

Samsung A70, Android 11

**Comment by jacko9000** [comment]
Crashes on launching the arm64-v8a variant in Android 11.  Here is the device logcat from the point when the app was launched:

12-15 08:51:00.856 I/ActivityTaskManager( 1349): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fox2code.mmm/.MainActivity bnds=[32,1335][235,1678]} from uid 1000

12-15 08:51:00.898 I/ActivityManager( 1349): Start proc 11750:com.fox2code.mmm/u0a3882 for pre-top-activity {com.fox2code.mmm/com.fox2code.mmm.MainActivity}

12-15 08:51:00.939 I/om.fox2code.mmm(11750): type=1400 audit(0.0:1517160): avc: denied { getattr } for path="/data/misc/profiles/cur/0/com.fox2code.mmm/primary.prof" dev="dm-5" ino=1261515 scontext=u:r:untrusted_app:s0:c42,c271,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1 app=com.fox2code.mmm

12-15 08:51:00.999 I/pool-4-thread-1(11750): type=1400 audit(0.0:1517161): avc: denied { read } for name="version" dev="proc" ino=4026532138 scontext=u:r:untrusted_app:s0:c42,c271,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=com.fox2code.mmm

12-15 08:51:00.999 I/pool-4-thread-1(11750): type=1400 audit(0.0:1517162): avc: denied { open } for path="/proc/version" dev="proc" ino=4026532138 scontext=u:r:untrusted_app:s0:c42,c271,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=com.fox2code.mmm

12-15 08:51:00.999 I/pool-4-thread-1(11750): type=1400 audit(0.0:1517163): avc: denied { getattr } for path="/proc/version" dev="proc" ino=4026532138 scontext=u:r:untrusted_app:s0:c42,c271,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=1 app=com.fox2code.mmm

12-15 08:51:01.019 I/RenderThread(11750): type=1400 audit(0.0:1517164): avc: denied { open } for path="/dev/__properties__/u:object_r:adbd_prop:s0" dev="tmpfs" ino=1204 scontext=u:r:untrusted_app:s0:c42,c271,c512,c768 tcontext=u:object_r:adbd_prop:s0 tclass=file permissive=1 app=com.fox2code.mmm

12-15 08:51:01.035 D/vulkan  (11750): searching for layers in '/data/app/~~I26klT78ysx-nXeBYSXHag==/com.fox2code.mmm-tMApMeq4Ybh39mLXKO3Vjw==/lib/arm64'

12-15 08:51:01.035 D/vulkan  (11750): searching for layers in '/data/app/~~I26klT78ysx-nXeBYSXHag==/com.fox2code.mmm-tMApMeq4Ybh39mLXKO3Vjw==/base.apk!/lib/arm64-v8a'

12-15 08:51:01.075 I/TetheringManager(11750): registerTetheringEventCallback:com.fox2code.mmm

12-15 08:51:01.109 I/ActivityManager( 1349): Start proc 11806:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i26 for  {com.fox2code.mmm/org.chromium.content.app.SandboxedProcessService0:0}

12-15 08:51:01.111 W/linker  (11750): Warning: "/data/app/~~I26klT78ysx-nXeBYSXHag==/com.fox2code.mmm-tMApMeq4Ybh39mLXKO3Vjw==/base.apk!/lib/arm64-v8a/libcronet.108.0.5359.95.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)

12-15 08:51:01.118 D/ConnectivityService( 1349): requestNetwork for uid/pid:13882/11750 NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ]

12-15 08:51:01.121 D/UntrustedWifiNetworkFactory( 1349): got request NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.121 D/WIFI_AWARE_FACTORY( 1349): got request NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.121 D/WifiNetworkFactory( 1349): got request NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.121 D/Ethernet( 1349): got request NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.122 D/PhoneSwitcherNetworkRequstListener(17373): got request NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.127 E/b0      (11750): 	at com.fox2code.mmm.background.BackgroundUpdateChecker.i(SourceFile:98)

12-15 08:51:01.127 E/b0      (11750): 	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:200)

12-15 08:51:01.150 D/ConnectivityService( 1349): requestNetwork for uid/pid:13882/11750 NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ]

12-15 08:51:01.152 D/Ethernet( 1349): got request NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.152 D/UntrustedWifiNetworkFactory( 1349): got request NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.152 D/WifiNetworkFactory( 1349): got request NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.153 D/WIFI_AWARE_FACTORY( 1349): got request NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.153 D/PhoneSwitcherNetworkRequstListener(17373): got request NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] with score 50 and providerId 133

12-15 08:51:01.192 D/om.fox2code.mm(11750): Successfully queried cache dir: /data/user_de/0/com.fox2code.mmm/code_cache

12-15 08:51:01.192 D/RenderScript(11750): Setting cache dir: /data/user_de/0/com.fox2code.mmm/code_cache

12-15 08:51:01.338 I/ActivityTaskManager( 1349): Displayed com.fox2code.mmm/.MainActivity: +478ms

12-15 08:51:01.759 E/AndroidRuntime(11750): Process: com.fox2code.mmm, PID: 11750

12-15 08:51:02.232 W/InputDispatcher( 1349): channel '8f75b6 com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

12-15 08:51:02.232 E/InputDispatcher( 1349): channel '8f75b6 com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

12-15 08:51:02.232 W/InputDispatcher( 1349): channel '18d28de com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd

12-15 08:51:02.232 E/InputDispatcher( 1349): channel '18d28de com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

12-15 08:51:02.250 D/ConnectivityService( 1349): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=438, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ], android.os.BinderProxy@20261c6)

12-15 08:51:02.251 D/ConnectivityService( 1349): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ], android.os.BinderProxy@9f22587)

12-15 08:51:02.251 D/ConnectivityService( 1349): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ], android.os.BinderProxy@f34cb4)

12-15 08:51:02.251 I/ActivityManager( 1349): Process com.fox2code.mmm (pid 11750) has died: fg  TOP 

12-15 08:51:02.251 D/ConnectivityService( 1349): releasing NetworkRequest [ TRACK_DEFAULT id=437, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] (release request)

12-15 08:51:02.251 I/WindowManager( 1349): WIN DEATH: Window{8f75b6 u0 com.fox2code.mmm/com.fox2code.mmm.MainActivity}

12-15 08:51:02.251 W/InputDispatcher( 1349): Attempted to unregister already unregistered input channel '8f75b6 com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)'

12-15 08:51:02.254 I/WindowManager( 1349): WIN DEATH: Window{18d28de u0 com.fox2code.mmm/com.fox2code.mmm.MainActivity}

12-15 08:51:02.254 W/InputDispatcher( 1349): Attempted to unregister already unregistered input channel '18d28de com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)'

12-15 08:51:02.256 D/ConnectivityService( 1349): releasing NetworkRequest [ TRACK_DEFAULT id=439, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 13882 AdministratorUids: [] RequestorUid: 13882 RequestorPackageName: com.fox2code.mmm] ] (release request)

12-15 08:51:02.259 I/WindowManager( 1349): WIN DEATH: Window{524e2ee u0 com.fox2code.mmm/com.fox2code.mmm.MainActivity}

12-15 08:51:02.259 W/InputDispatcher( 1349): Attempted to unregister already unregistered input channel '524e2ee com.fox2code.mmm/com.fox2code.mmm.MainActivity (server)'

12-15 08:51:02.266 W/ActivityTaskManager( 1349): Force removing ActivityRecord{212e196 u0 com.fox2code.mmm/.MainActivity t7480}: app died, no saved state

---- 15 Dec 2022 08:51:53 ----

**Comment by Fox2Code** [comment]
Bug is caused by an issue in AndroidX implementation of SwitchCompat 
I added a workaround in FoxCompat: https://github.com/Fox2Code/FoxCompat/commit/4be39ba01810b855ff5fbd474428784c35d04e7e
Also this commit should have fixed the crash: https://github.com/Fox2Code/FoxMagiskModuleManager/commit/e0ecd8f96083cc4ffa471fde7338a743529a5843

**Comment by Yamancorum** [comment]
+1 same crash my phone: Android 7.1.2, custom rom LG g4c, app not open, merhaba 0.6.8 open but it have some crash when change Settings. I waiting for fix

**Comment by Yamancorum** [comment]
![Screenshot_20221215-125056](https://user-images.githubusercontent.com/120640377/207828257-1c8d5706-7b01-47de-a008-416668b9e1b3.png)

**Comment by unofr** [comment]
Same on redmi note 4x with lineageos Android 11 ROM.
Go back to old release

**Comment by Daviteusz** [comment]
For me the new version works on a13 oos13 but debug builds no longer work. They crash on startup.

**Comment by Tomadock** [comment]
Clearing Storage, uninstalling, and reinstalling fixed this issue for me.

**Comment by sconim** [comment]
Same here - it crashes with the error message shown above by Yamancorun. Phone Samsung S20, Android 10.

**Comment by HyperCriSiS** [comment]
FATAL EXCEPTION: main
Process: com.fox2code.mmm, PID: 422
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.text.StaticLayout.<init>(StaticLayout.java:455)
	at androidx.appcompat.widget.SwitchCompat.c(SourceFile:28)
	at androidx.appcompat.widget.SwitchCompat.onMeasure(SourceFile:11)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1412)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:452)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:150)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:155)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2219)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
