### ISSUE TITLE
root access bug

### ISSUE THREAD

**Issue by LitoHDD** [Fox2Code/FoxMagiskModuleManager#303]
In the previous version it worked great. But in this when I install it and give it root permissions then a red banner appears which says that root is not detected. If you need logs or more information, do not hesitate to contact me. My device on a Xiaomi Redmi K20 PRO. So for the moment I go back to version v1.1.0

 - Device: Xiaomi Redmi K20 PRO
 - OS: Evolution X 7.8 (Rooted)
 - App Version 2.0.1

**Comment by andigenn** [comment]
Same here.
Device: Xiaomi Mi 8 Global
OS: MIUI 12.0.3 (Rooted)
App Version 2.0.1

**Comment by LitoHDD** [comment]
> Hasta ahora es exclusivo de miui, lo que indicaría otra rareza con Xiaomi y su software. No obstante, no podemos reproducir, por lo que actualmente no podemos solucionar ningún problema que pueda estar causando esto.

I don't use MIUI I use a custom rom as mentioned in the first report

**Comment by VSeryi** [comment]
Same here.
Device: Oneplus 7T
OS: YAAP 13-Tripoli-hotdogb-20230426 (Rooted - Magisk 26.1)
App Version 2.0.1

**Comment by 28Black** [comment]
Same for me as well, will return meanwhile to the previous working version from december. 

Device: OnePlus 6
OS: Jaguar ROM (Android 11, GrapheneOS / LineageOS based; Magisk 26.1)
App Version: 2.0.1

**Comment by arikyo07** [comment]
Same happens here
In previous versions it works fine

Device: Redmi Note 9S
OS: Pixel Experience (Android 13, Magisk 26100)
PixelExperience_Plus_miatoll-13.0-20230402-1037-OFFICIAL
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11338070/logs.txt)

**Comment by Qattos** [comment]
Same thing for me.
Worked as it should on previous versions. 
Device: Xperia XZ
OS: Latest stock ROM 8.0 (2018) (rooted with Magisk)

**Comment by henosch** [comment]
The debug Version get root Access.

**Comment by Qattos** [comment]
Unfortunately the debug version still can't use root access despite asking for it.

Here's my [Log](https://pastebin.com/yDxhFVCS)

**Comment by andigenn** [comment]
In my case too the debug version still can't use root access despite asking for it.
Here's my [logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11339824/logs.txt)

**Comment by JangoPhat** [comment]
where to find debug version?

**Comment by IZ2QDH** [comment]
Tested both version 2.0.1 and debug version. Issue reproduced.
Device: Poco F1
OS: LineageOS 20.0
Android Version: 13
Lygisk 26.1
Debug version logs [here](https://pastebin.com/ZQzJDcFZ)

**Comment by abun880007** [comment]
Same issue here
Device Pixel 7 Pro
OS: Android 14 Beta 1.1
Magisk Delta Canary 25210

**Comment by VSeryi** [comment]
> @28Black @VSeryi @andigenn @arikyo07 whoever else was having the issue, does this build work any better?
> 
> https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4815009696
> 
> If not, please share the logs from settings -> save logs and share

Same error.

Debug logs:
[logs (2).txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11343188/logs.2.txt)

**Comment by IZ2QDH** [comment]
> Any luck with this one?
> 
> https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4819719293

Nope for me, granted root permission but app says it's denied
Logs [here](https://pastebin.com/fhpUnFUy)

**Comment by Skaynod** [comment]
I accepted Root permission but on the app it says it was denied
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11345861/logs.txt)

**Comment by andigenn** [comment]
On my MI 8 the issue still persists.
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11350114/logs.txt)

**Comment by IZ2QDH** [comment]
> https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4826124597
> 
> Another build to test

issue stil present
Logs [HERE](https://pastebin.com/dK1Kadz7)

**Comment by zgfg** [comment]
I have two Xiaomi phones, one with MIUI 12.5 / Android 11 and another with MIUI 13 / Android 12

On both phones root is properly granted - I will attach screenshots captured when starting Fox MMM, popping up that root was granted

And indeed, I can disable and uninstall modules (would not work without root)

But when I try to install ANY module, Fox MMM crashes for me.
On both my phones, for ANY module - even those modules that I already have installed (ie, nothing wrong with the modules)

I just sent you two crash reports from inside the Fox MMM app (fgmicro@gmail.com)

![IMG_20230428_205109](https://user-images.githubusercontent.com/51943147/235231335-f913bc8a-50fd-4bc6-b353-5ab30f966bb0.jpg)
![Screenshot_2023-04-28-20-53-18-004_com fox2code mmm](https://user-images.githubusercontent.com/51943147/235231396-d47a0126-c341-4b0c-aabb-027be0c1ef4b.jpg)
![IMG_20230428_210342](https://user-images.githubusercontent.com/51943147/235231969-e8996252-5c32-4b29-80eb-442686c41ea7.jpg)

**Comment by Qattos** [comment]
> https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4836183745
> 
> Another test build up for y'all. Sorry to keep asking but I don't have access to a device with the issue.

Won't even open, immediately crashing on my Xperia XZ (8.0)

**Comment by arikyo07** [comment]
When I run the app it crashes immediately. He didn't provide a log in his comment above, so I'll leave one.

Device: Xiaomi Redmi Note 9S
OS: Pixel Experience (Android 13, Magisk 26100)
PixelExperience_Plus_miatoll-13.0-20230402-1037-OFFICIAL

<details><summary>Crash Log</summary>
<pre>
04-29 13:03:21.516  3154  3154 E AndroidRuntime: Process: com.fox2code.mmm.debug, PID: 3154
04-29 13:03:21.516  3154  3154 E AndroidRuntime: java.lang.ExceptionInInitializerError
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1245)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6751)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7925)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method &#39;android.content.Context com.fox2code.mmm.MainApplication.getApplicationContext()&#39; on a null object reference
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	at com.fox2code.mmm.MainApplication.&lt;clinit&gt;(MainApplication.java:109)
04-29 13:03:21.516  3154  3154 E AndroidRuntime: 	... 16 more
</pre>
</details>

**Comment by arikyo07** [comment]
Unfortunately, it doesn't work yet.

Device: Xiaomi Redmi Note 9S
OS: Pixel Experience (Android 13, Magisk 26100)
PixelExperience_Plus_miatoll-13.0-20230402-1037-OFFICIAL

Here is my log.
[logs (1).txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11358405/logs.1.txt)

**Comment by andigenn** [comment]
It doesn't work yet.
My [logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11358493/logs.txt)

**Comment by osm0sis** [comment]
Would checking out another open source root app project be helpful? I know AdAway has been pretty up-to-date on libsu, and it doesn't seem to have any issues detecting or requesting root on any of my devices: https://github.com/AdAway/AdAway

**Comment by VSeryi** [comment]
> Again, those who are willing
> 
> https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4839735163

:S Its still not working

[logs (5).txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11360408/logs.5.txt)

PS. Thanks for your work!

**Comment by arikyo07** [comment]
It works fine!!

________________________________
差出人: Androidacy Service Account ***@***.***>
送信日r: 2023年4月30日 12:00
宛先: Fox2Code/FoxMagiskModuleManager ***@***.***>
CC: AriKyo KaneDa（金田　sb） ***@***.***>; Mention ***@***.***>
件名: Re: [Fox2Code/FoxMagiskModuleManager] ROOT ACCESS BUG (Issue #303)


Yet another yet another

https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4841982502

―

**Comment by andigenn** [comment]
It works fine!
Thanks for your work!

**Comment by osm0sis** [comment]
Can confirm working well on my old Nexus 7 2013 with the latest arm CI build. 🎉
