### ISSUE TITLE
[BUG] Crash on installing any module

### ISSUE THREAD

**Issue by Prototik** [Fox2Code/FoxMagiskModuleManager#309]
```
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.installer.InstallerActivity}: java.lang.ClassCastException: com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton cannot be cast to vh
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassCastException: com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton cannot be cast to vh
	at com.fox2code.mmm.installer.InstallerActivity.onCreate(SourceFile:377)
	at android.app.Activity.performCreate(Activity.java:8311)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
```
Android 13, MMM latest from actions for master branch

**Comment by zgfg** [comment]
I have the same problem on both my phones (A11 and A12) , just sent you crash reports from inside Fox MMM

Previous versions of Fox MMM app were able to correctly install the modules

Now it crashes. Root was properly granted
![IMG_20230428_205109](https://user-images.githubusercontent.com/51943147/235232641-2e13cf66-9038-47d3-82f0-3f5e3aaa7530.jpg)
![IMG_20230428_210342](https://user-images.githubusercontent.com/51943147/235232661-de9f9d34-cc54-4e8f-8d5b-ca92201c1ba5.jpg)
![Screenshot_2023-04-28-20-53-18-004_com fox2code mmm](https://user-images.githubusercontent.com/51943147/235232697-bfe93cbc-6777-470b-a889-250c8b9127b8.jpg)

**Comment by mrkylegp** [comment]
Same issue here. Glad a fix is on the way!

**Comment by zgfg** [comment]
Ok, I tried this Action build and it works now, thanks
https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4826124597
